encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("newpage", views.newpage, name="newpage"),
    path("edit", views.edit, name="edit"),
    path("update", views.update, name="update"),
    path("random", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponse
from django.shortcuts import render
from markdown2 import markdown
from random import randint

from . import util

def index(request):
    # display of all available entries
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(), "header": "All Pages"
    })

def entry(request, title):
    # check if entry exists
    if util.get_entry(title):
        # valid_entry is used to display or hide the edit button
        valid_entry = True
        list_entry = util.get_entry(title)
        return render(request, "encyclopedia/entry.html", {
            "title": title, 
            "list_entry": markdown(list_entry),
            "valid_entry": valid_entry
        })        
    else:
        valid_entry = False
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "list_entry": title+"<h4>Entry not found</h4>",
            "valid_entry": valid_entry
        })

def search(request):
    # lookup list of entries and make lowercase
    entries = util.list_entries()
    entries_lwr = [i.lower() for i in entries]

    # receive search query from form 
    query = request.POST.get('q')

    # check if list of entries contains query non case sensitive
    if query.casefold() in entries_lwr:
        query = util.get_entry(query)
        return render(request, "encyclopedia/entry.html", {
            "title": query, 
            "list_entry": markdown(query)
        })  

    # check if list of entries contains substring of query
    elif query:
        result = [search for search in entries if query.casefold() in search.casefold()]  
        return render(request, "encyclopedia/index.html", {
        "entries": result, 
        "header": "Search Results"
        })
     
    # return to index page if query not found    
    else:
        return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "header": "All Pages"
        })
    
def newpage(request):
    if request.method == "POST":
        # get new title and entry
        
        new_title = request.POST.get('title')
        new_entry = request.POST.get('text')

        # check if title already exists , print error mesage if yes
        if new_title:
            list_entries = util.list_entries()
            entries_lwr = [i.lower() for i in list_entries]
            if new_title.casefold() in entries_lwr:
                error_msg = new_title + " - this entry is already available"
                return render(request, "encyclopedia/entry.html", {
                    "error": error_msg
                })

            else:
                # create new file from title and entry
                with open("entries/%s.md" % new_title, "w") as new_file:
                    new_file.write("# %s\n\n" % new_title)
                    new_file.write(new_entry + "\n")
                list_entry = util.get_entry(new_title)

                # display new entry
                return render(request, "encyclopedia/entry.html", {
                    "title": new_title, "list_entry": markdown(list_entry)
                }) 
        else:
            return render(request, "encyclopedia/index.html", {
                "entries": util.list_entries(), "header": "All Pages"
            })
    else:
        return render(request, "encyclopedia/newpage.html")
    
def edit(request):
    # get current entry to be edited and send to edit page
    title = request.POST.get('edit')
    entry = util.get_entry(title)
    return render(request, "encyclopedia/edit.html",{
        "title": title, "entry": entry
    })

def update(request):
    # safe entry to file (overwrites excisting file)
    title = request.POST.get('title')
    entry = request.POST.get('text')
    with open("entries/%s.md" % title, "w") as file_for_update:
        file_for_update.write(entry)
    list_entry = util.get_entry(title)
    return render(request, "encyclopedia/entry.html", {
        "title": title, "list_entry": markdown(list_entry)
    })   

def random(request):
    # request list of all titles in database
    titles = util.list_entries()
    # create random number by using length of list
    rndm = randint(0, (len(titles)- 1))
    # identify title using the random number
    random_title = titles[rndm]
    # get text entry asocoiated with the title 
    random_entry = util.get_entry(random_title)
    # display random entry
    return render(request, "encyclopedia/entry.html", {
        "title": random_title, 
        "list_entry": markdown(random_entry),
        "valid_entry": True
    })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ title }}
{% endblock %}

{% block body %}
    
    <form action="{% url 'encyclopedia:update' %}" method="post">
        {% csrf_token %}
        <input type="text" value="{{ title }}" name="title" style="width: 80%; margin-bottom: 10px;">
        <textarea rows="5" name="text" style="height: 100%; width: 80%;">{{ entry }}</textarea>
        <div>
            <input type="submit" value="Save">
        </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    
    <div>
        {{ list_entry|safe }}
        {{ error }}
    </div>
    <form action="{% url 'encyclopedia:edit' %}" method="post">
        {% csrf_token %}
        <input type="hidden"  name="edit" value="{{ title }}">
        {% if valid_entry == True %}
        <div>
            <input type="submit" value="Do you want to edit this entry?">
        </div>
        {% endif %}
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if entries %}
    <h2>{{ header }}</h2>
    {% else %}
    <h2>No entries found</h2>
    {% endif %}

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input class="button" type="submit" value="Search">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}

    <form action="{% url 'encyclopedia:newpage' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Title" name="title" style="width: 80%; margin-bottom: 10px;">
        <textarea rows="5" name="text" style="height: 100%; width: 80%"></textarea>
        <div>
            <input type="submit" value="Save">
        </div>
    </form>

{% endblock %}